# Metadata for the AutoBlind plugin
plugin:
    # Global plugin attributes
    type: system                # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Zustandsautomat für SmarthomeNG'
        en: 'Finite state machine for SmarthomeNG'
    mainainer: i-am-offline
    documentation: https://github.com/i-am-offline/smarthome.plugin.autoblind/wiki

    version: 1.4.0
    sh_minversion: 1.4.0
    multi_instance: False
    classname: AutoBlind

plugin_parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

item_attributes:
    # Definition of item attributes defined by this plugin